{% set version = environ.get('PYTHON_VERSION', '0.0.0.1') %}

package:
  name: qsharp
  version: "{{ version }}"

source:
  - path:    ../../
    folder:  src

requirements:
  build:
    - python
    - setuptools
    - jupyter
    - jupyter_client<5.3.3
    - iqsharp={{ version }}

  run:
    - python
    - iqsharp={{ version }}

build:
  script: |
    powershell -NoProfile src/conda-recipes/qsharp/build.ps1 # [win]
    pwsh src/conda-recipes/qsharp/build.ps1 # [not win]

test:
  requires:
    - python
    - iqsharp={{ version }}
    - pytest

  source_files:
    - src/conda-recipes/qsharp/test.ps1
    - src/conda-recipes/qsharp/tests.py

  commands:
    - powershell -NoProfile src/conda-recipes/qsharp/test.ps1 # [win]
    - pwsh src/conda-recipes/qsharp/test.ps1 # [not win]

about:
  home: https://docs.microsoft.com/quantum
  license: MIT
  summary: Python client for Q#, a domain-specific quantum programming language.
  description: |
    For details on how to get started with Python and Q#, please see the guide at https://docs.microsoft.com/quantum/install-guide/python.
    You can also try our Quantum Computing Fundamentals learning path (https://aka.ms/learnqc) to get familiar with the basic concepts
    of quantum computing, build quantum programs, and identify the kind of problems that can be solved.
  dev_url: https://github.com/microsoft/iqsharp
  doc_url: https://docs.microsoft.com/quantum/install-guide/python
