package:
  name: pwsh
  version: "6.2.2"

build:
  # Note that we do not need to look for prefixes with this package, as it is a
  # .NET Core Global Tool; any prefixing is done in the dotnetcore-sdk package itself.
  # Disabling prefixing fixes a macOS-specific bug and makes building this package much
  # faster.
  ignore_prefix_files: True

requirements:
  build:
    - dotnetcore-sdk=2.2.401

  run:
    - dotnetcore-sdk=2.2.401

about:
  home: https://github.com/PowerShell/PowerShell
