package:
  name: pwsh
  version: "6.2.2"

build:
  detect_binary_files_with_prefix: False
  ignore_prefix_files:
    - libmi.dylib

requirements:
  build:
    - dotnetcore-sdk=2.2.401

  run:
    - dotnetcore-sdk=2.2.401

about:
  home: https://github.com/PowerShell/PowerShell
