package:
  name: dotnetcore-sdk
  version: "2.2.401"

source:
  - url: https://dot.net/v1/dotnet-install.sh  # [not win]
    sha256: b5b2340b159fa644e6a77ed54afc7fa9667fa6947caedf71c1e8c2d667e0632e # [not win]
  - url: https://dot.net/v1/dotnet-install.ps1 # [win]
    sha256: a0b41e631cfd67cdf07a97a68be9b7da22df002a0e60110685c8a4ab5e2eb883 # [win]

# test:
#   imports:
#     -

about:
  home: https://docs.microsoft.com/dotnet/core/
