package:
  name: iqsharp
  version: "0.8"

source:
  - path:    ../../
    folder:  iqsharp

requirements:
  build:
    - python
    - setuptools
    - dotnetcore-sdk=2.2.401
    - pwsh>=6.2.2 # [not win]
    - jupyter

  run:
    - python
    - jupyter

# test:
#   imports:
#     -

about:
  home: https://docs.microsoft.com/quantum
