package:
  name: iqsharp
  version: "0.8"

source:
  - path:    ../../
    folder:  iqsharp
    patches:
      # We need to disable <PackAsTool>true</PackAsTool> when publishing on macOS
      # and Linux due to https://github.com/dotnet/cli/issues/10607. This should
      # be resolved with .NET Core SDK 3.0 and later.
      - bug-10607-workaround.patch # [not win]

requirements:
  build:
    - python
    - setuptools
    - dotnetcore-sdk=2.2.401
    - pwsh>=6.2.2 # [not win]
    - jupyter

  run:
    - python
    - jupyter

test:
  requires:
    - pwsh>=6.2.2 # [not win]
    - jupyter

  source_files:
    - iqsharp/conda-recipes/iqsharp/test.ps1

  commands:
    - powershell -NoProfile iqsharp/conda-recipes/iqsharp/test.ps1 # [win]
    - pwsh iqsharp/conda-recipes/iqsharp/test.ps1 # [not win]

about:
  home: https://docs.microsoft.com/quantum
